<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://hospital/agenda/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:agenda="http://hospital/agenda/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:hos="http://hospital/schema/">
	<!-- type definitions -->
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://hospital/agenda/">
			<xsd:import schemaLocation="./hospital.xsd" namespace="http://hospital/schema/" />
		</xsd:schema>
	</types>
	<message name="scheduleTreatmentRequest">
		<part name="treatmentPlan" element="hos:AgendaRequest" />
	</message>
	<message name="scheduleTreatmentResponse">
		<part name="treatmentScheduling" element="hos:AgendaResponse" />
	</message>

	<!-- portType definitions -->
	<portType name="agenda">
		<operation name="scheduleTreatment">
			<input message="agenda:scheduleTreatmentRequest" />
			<output message="agenda:scheduleTreatmentResponse" />
		</operation>
	</portType>

	<!-- binding definition -->
	<binding name="AgendaBinding" type="agenda:agenda">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="scheduleTreatment">
			<soap:operation soapAction="http://hospital/agenda/scheduleTreatment" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<!-- Service defines the address of Web service -->
	<service name="AgendaService">
		<port binding="agenda:AgendaBinding" name="agenda">
			<soap:address location="http://localhost:9080/hospital.agenda/services/AgendaService" />
		</port>
	</service>
</definitions>