<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://hospital/room/" xmlns:hos="http://hospital/schema/"
	xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:room="http://hospital/room/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
	<!-- type definitions -->
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://hospital/room/">
			<xsd:import schemaLocation="./hospital.xsd" namespace="http://hospital/schema/" />
			
		</xsd:schema>
	</types>
	
	<message name="findRoomRequest">
		<part name="items" element="hos:Items"/>
	</message>
	<message name="findRoomResponse">
		<part name="roomIDs" element="hos:RoomIDs"/>
	</message>


	<!-- portType definitions -->
	<portType name="room">
		<operation name="findRoom">
			<input message="room:findRoomRequest" />
			<output message="room:findRoomResponse" />
		</operation>
	</portType>
	
	<plnk:partnerLinkType name="roomLinkType">
		<plnk:role name="room" portType="room:room" />
	</plnk:partnerLinkType>

	<!-- binding definition -->
	<binding name="RoomBinding" type="room:room">


		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="findRoom">
			<soap:operation
				soapAction="http://hospital/room/findRoom" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<!-- Service defines the address of Web service -->
	<service name="RoomService">
		<port binding="room:RoomBinding" name="room">
			<soap:address
				location="http://localhost:9080/hospital.room/services/RoomService" />
		</port>
	</service>
</definitions>