<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://hospital/scheduling/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:scheduling="http://hospital/scheduling/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:agenda="http://hospital/agenda/" xmlns:agendaCallback="http://hospital/agendaCallback/"
	xmlns:doctor="http://hospital/doctor/" xmlns:patient="http://hospital/patient/" xmlns:room="http://hospital/room/" xmlns:hos="http://hospital/schema/">

	<!-- type definitions -->
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://hospital/scheduling/">
			<xsd:import schemaLocation="./hospital.xsd" namespace="http://hospital/schema/" />
		</xsd:schema>
	</types>
	<message name="scheduleTreatmentRequest">
		<part name="treatmentPlan" element="hos:SchedulingRequest" />
	</message>
	<message name="scheduleTreatmentResponse">
		<part name="treatmentSchedule" element="hos:SchedulingResponse" />
	</message>

	<!-- portType definitions -->
	<portType name="scheduling">
		<operation name="scheduleTreatment">
			<input message="scheduling:scheduleTreatmentRequest" />
			<output message="scheduling:scheduleTreatmentResponse" />
		</operation>
	</portType>

	<!-- binding definition -->
	<binding name="SchedulingBinding" type="scheduling:scheduling">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="scheduleTreatment">
			<soap:operation soapAction="http://hospital/scheduling/scheduleTreatment" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<!-- Service defines the address of Web service -->
	<service name="SchedulingService">
		<port binding="scheduling:SchedulingBinding" name="scheduling">
			<soap:address location="http://localhost:9080/hospital.scheduling/services/BikeService" />
		</port>
	</service>
</definitions>